name: Common CI - Reusable Workflow

on:
  workflow_call:
    inputs:
      type_pipeline:
        description: 'What pipeline is triggering the common_ci.yml'
        required: true
        type: string

jobs:
  test-contract:

    runs-on: ubuntu-22.04

    steps:
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        PACT_BROKER_TOKEN: op://CI-CD/pactflow/PACT_BROKER_TOKEN
    - name: Project checkout - Continuous Integration
      if: inputs.type_pipeline == 'continuous_integration'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Project checkout - Continuous Delivery
      if: inputs.type_pipeline == 'continuous_delivery'
      uses: actions/checkout@v3
    - run: docker-compose build test-contract
    - name: Run contract test
      run: make test-contract
      env:
        PACT_BROKER_TOKEN: ${{ env.PACT_BROKER_TOKEN }}

  lint:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Node.js Setup
      uses: actions/setup-node@v3
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  commit-lint:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v5
      with:
        helpURL: https://github.com/ServeRest/ServeRest/blob/trunk/.github/CONTRIBUTING.md

  dockerfile-lint:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Validate production Docker Hub dockerfile (Dockerfile)
      run: docker run --rm -i hadolint/hadolint < Dockerfile
    - name: Validate production Google Cloud dockerfile (Dockerfile.gcloud)
      run: docker run --rm -i hadolint/hadolint < Dockerfile.gcloud
    - name: Validate dev dockerfile (Dockerfile.dev)
      run: docker run --rm -i hadolint/hadolint < Dockerfile.dev
    - name: Validate terratest dockerfile (Dockerfile.terratest)
      run: docker run --rm -i hadolint/hadolint < Dockerfile.terratest

  test-unit:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        DD_API_KEY: op://CI-CD/Datadog/DD_API_KEY
    - run: docker-compose build test-unit
    - name: Run Unit Test
      run: make test-unit
      env: # Datadog "CI Tests" variables
        DD_CIVISIBILITY_AGENTLESS_ENABLED: true
        DD_API_KEY: ${{ env.DD_API_KEY }}
        DD_SITE: datadoghq.eu
        NODE_OPTIONS: '-r dd-trace/ci/init'
        DD_GIT_REPOSITORY_URL: git@github.com:ServeRest/ServeRest.git
        DD_GIT_COMMIT_SHA:  ${{ github.sha }}
        DD_GIT_BRANCH: ${{ github.ref_name }}
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-unit
        retention-days: 1
        path: coverage-unit/lcov.info

  test-integration:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        DD_API_KEY: op://CI-CD/Datadog/DD_API_KEY
    - run: docker-compose build test-integration
    - name: Run Integration Test
      run: make test-integration
      env: # Datadog "CI Tests" variables
        DD_CIVISIBILITY_AGENTLESS_ENABLED: true
        DD_API_KEY: ${{ env.DD_API_KEY }}
        DD_SITE: datadoghq.eu
        NODE_OPTIONS: '-r dd-trace/ci/init'
        DD_GIT_REPOSITORY_URL: git@github.com:ServeRest/ServeRest.git
        DD_GIT_COMMIT_SHA:  ${{ github.sha }}
        DD_GIT_BRANCH: ${{ github.ref_name }}
    - uses: actions/upload-artifact@v3
      with:
        name: coverage-integration
        retention-days: 1
        path: coverage-integration/lcov.info

  test-e2e:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        DD_API_KEY: op://CI-CD/Datadog/DD_API_KEY
    - run: docker-compose build run-app-e2e
    - run: docker-compose build test-e2e-localhost
    - name: Run E2E test in locally built docker image
      run: make test-e2e-localhost
      env: # Datadog "CI Tests" variables
        DD_CIVISIBILITY_AGENTLESS_ENABLED: true
        DD_API_KEY: ${{ env.DD_API_KEY }}
        DD_SITE: datadoghq.eu
        NODE_OPTIONS: '-r dd-trace/ci/init'
        DD_GIT_REPOSITORY_URL: git@github.com:ServeRest/ServeRest.git
        DD_GIT_COMMIT_SHA:  ${{ github.sha }}
        DD_GIT_BRANCH: ${{ github.ref_name }}

  sonarcloud:
    needs: [test-unit, test-integration]

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Download unit test artifact
      uses: actions/download-artifact@v3
      with:
        name: coverage-unit
        path: coverage-unit
    - name: Download integration test artifact
      uses: actions/download-artifact@v3
      with:
        name: coverage-integration
        path: coverage-integration
    - name: Merge coverage report
      run: npm run merge-lcov
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        SONAR_TOKEN: op://CI-CD/sonar/SONAR_TOKEN
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

  test-infra-docker:

    runs-on: ubuntu-22.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v3
    - run: docker-compose build test-infra
    - name: Run infra test
      run: make test-infra

