name: Contract Test Triggered by Consumer

on:
  repository_dispatch:
    types: [pact-changed]

jobs:
  test-contract:

    runs-on: ubuntu-22.04

    steps:
    - name: Load secrets from 1password
      uses: 1password/load-secrets-action@v1
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        PACT_BROKER_TOKEN: op://CI-CD/pactflow/PACT_BROKER_TOKEN
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.client_payload.providerProductionSha }}
    - run: docker-compose build test-contract
    - name: Run contract test
      run: make test-contract
      env:
        PACT_URL: ${{ github.event.client_payload.pactUrl }}
        PACT_BROKER_TOKEN: ${{ env.PACT_BROKER_TOKEN }}
