name: Deploy docs on serverest.dev

on:
  push:
    branches: [trunk, umbler]

jobs:
  deploy-doc:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Upload serverest.dev via ftp
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: geonosis02.umbler.host
        ftp-username: serverest-dev
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: docs
